# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: probie's blog
subtitle: ''
keywords:

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://probiecoder.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: "fluid"

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:duwei0227/document.git
  branch: gh-pages
navbar:
  blog_title: probie's blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }

force_https: true
dark_mode:
  enable: true
  default: auto
index:
  auto_excerpt:
    enable: false  # 开启自动摘要
  post_url_target: _blank
  # banner_img: /img/bg/home.webp
  slogan:
    enable: false
    text: 这是一条 Slogan
    api:
      enable: true
      # url: "https://api.eatrice.top/reading/"
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

# category:
#   banner_img: /img/bg/category.webp
#   banner_img_height: 0

# archive:
#   banner_img: /img/bg/archive.webp
#   banner_img_height: 0

post:
  banner_img: 
#   banner_img_height: 0

about:
  # avatar: /img/avatar.png
  # banner_img: /img/bg/about.webp
  # banner_img_height: 0
  name: "我"
  intro: "Java工程师"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 150 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
  
# 压缩 Hexo 生成的文件
# all_minifier: true

footer:
  content: "@probiecoder 2024"
favicon: /img/favicon.png

lazyload:
  enable: true
  onlypost: false
  offset_factor: 2

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'github-dark-dimmed'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true
